### ISSUE TITLE
Allow negative numbers

### ISSUE THREAD

**Issue by deltaidea** [mangudai/mangudai#31]
Some attributes accept negative numbers:

```RMS
create_land {
  clumping_factor -50%
}
```

This seems to cause extreme results in all such attributes. It's OK not to tell about negative numbers in the docs, but the parser should still be able to work with them.

**Comment by goto-bus-stop** [comment]
`resource_delta` can take a negative number too, and does something useful with it (`create_object DEER { resource_delta -174 }` for deer with 1 food)
