### ISSUE TITLE
`if` should not require newline after condition

### ISSUE THREAD

**Issue by goto-bus-stop** [mangudai/mangudai#34]
Hi, this is a super cool project!

I noticed one issue with the parser on the [FenCrazy](https://gist.github.com/goto-bus-stop/5a4ca7fc14fe5b380b8498632a89a578) map, which is intended to test AIs in weird conditions, and IME is a decent test script for RMS tools as well :)

It errors on this snippet (and a few similar ones throughout the script):

```
if     NO_LEFT     #define NO_RIGHT
elseif SMALL_LEFT  #define SMALL_RIGHT
elseif MEDIUM_LEFT #define MEDIUM_RIGHT
elseif LARGE_LEFT  #define LARGE_RIGHT
elseif XLARGE_LEFT #define XLARGE_RIGHT
endif
```

saying "Unexpected token `#define`". The `elseif`s are apparently OK, when I add a newline after the `if` condition it parses fine.

---

Somewhat unrelatedly, that map also contains this strange construct: https://gist.github.com/goto-bus-stop/5a4ca7fc14fe5b380b8498632a89a578#file-fencrazyv6n1-rms-L3259-L3267

```
if KF_TC_NO_WALL
elseif KF_TC_P_WALL
 create_object PALISADE_WALL
elseif KF_TC_W_WALL
 create_object WALL
elseif KF__TC_F_WALL
 create_object FORTIFIED_WALL
endif
{
  /* block contents */
}
```

A standalone `{}` block parses OK in AoC, I _think_ it treats the attributes as if they were a part of the previous block, because the AoC parser is a bit (very) quirky. It's probably fine not to support this in the parser and make authors fix their script instead.

**Comment by deltaidea** [comment]
Thanks for your help!

Added support for both:
- stuff on the same line after `if`,
- empty `if`/`elseif`/`else` branches in `ConditionalCommand`.

Yeah, my initial guess was that empty branches are treated as "ignore this command block completely" but now I'm sure. In any case, if something is supported by the game, it should be supported here. If we don't know how it works, it still shouldn't be a game stopper. 😄
